/** Ideal joint-angle targets for common yoga postures (degrees). */

export const POSES = [
  {
    name: "Mountain Pose",
    sanskrit: "Tadasana",
    difficulty: "beginner",
    description: "Stand tall, feet together, arms relaxed at your sides.",
    tips: [
      "Distribute weight evenly on both feet",
      "Lengthen through the crown of your head",
      "Relax shoulders away from ears",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 10,
      right_shoulder: 10,
      left_hip: 175,
      right_hip: 175,
      left_knee: 175,
      right_knee: 175,
    },
  },
  {
    name: "Raised Arms Pose",
    sanskrit: "Urdhva Hastasana",
    difficulty: "beginner",
    description: "Stand tall and reach both arms straight up overhead.",
    tips: [
      "Keep arms close to ears",
      "Do not arch the lower back",
      "Press feet firmly into the ground",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 165,
      right_shoulder: 165,
      left_hip: 175,
      right_hip: 175,
      left_knee: 175,
      right_knee: 175,
    },
  },
  {
    name: "Warrior II",
    sanskrit: "Virabhadrasana II",
    difficulty: "beginner",
    tolerance: 1.15,
    description: "Front knee bent ~90°, arms stretched out to the sides.",
    tips: [
      "Front thigh parallel to the floor if possible",
      "Back foot angled ~45°",
      "Gaze over front fingertips",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 90,
      right_shoulder: 90,
      left_hip: 100,
      right_hip: 155,
      left_knee: 95,
      right_knee: 170,
    },
  },
  {
    name: "Warrior I",
    sanskrit: "Virabhadrasana I",
    difficulty: "beginner",
    tolerance: 1.15,
    description: "Lunge with front knee bent, arms raised overhead.",
    tips: [
      "Square hips toward the front",
      "Front knee tracks over ankle",
      "Reach arms up, palms facing",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 160,
      right_shoulder: 160,
      left_hip: 100,
      right_hip: 150,
      left_knee: 100,
      right_knee: 170,
    },
  },
  {
    name: "Tree Pose",
    sanskrit: "Vrksasana",
    difficulty: "beginner",
    description: "Balance on one leg; other foot on inner thigh, hands together.",
    tips: [
      "Place foot on calf or thigh — never on the knee",
      "Find a fixed gaze point (drishti)",
      "Press standing foot into the floor",
    ],
    angles: {
      left_elbow: 90,
      right_elbow: 90,
      left_shoulder: 45,
      right_shoulder: 45,
      left_hip: 175,
      right_hip: 100,
      left_knee: 175,
      right_knee: 50,
    },
  },
  {
    name: "Goddess Pose",
    sanskrit: "Utkata Konasana",
    difficulty: "beginner",
    tolerance: 1.2,
    description: "Wide stance, knees bent, thighs open, arms in cactus shape.",
    tips: [
      "Knees track over toes",
      "Keep spine tall",
      "Engage core and glutes",
    ],
    angles: {
      left_elbow: 90,
      right_elbow: 90,
      left_shoulder: 90,
      right_shoulder: 90,
      left_hip: 110,
      right_hip: 110,
      left_knee: 100,
      right_knee: 100,
    },
  },
  {
    name: "Chair Pose",
    sanskrit: "Utkatasana",
    difficulty: "beginner",
    tolerance: 1.3,
    description: "Sit back as if into a chair; arms reach up.",
    tips: [
      "Weight in the heels",
      "Knees behind toes",
      "Chest lifted, core engaged",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 155,
      right_shoulder: 155,
      left_hip: 100,
      right_hip: 100,
      left_knee: 100,
      right_knee: 100,
    },
  },
  {
    name: "Downward Dog",
    sanskrit: "Adho Mukha Svanasana",
    difficulty: "beginner",
    tolerance: 1.2,
    description: "Inverted V — hands and feet on floor, hips high.",
    tips: [
      "Press hands firmly, fingers spread",
      "Lengthen spine",
      "Heels toward floor (gentle)",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 160,
      right_shoulder: 160,
      left_hip: 80,
      right_hip: 80,
      left_knee: 170,
      right_knee: 170,
    },
  },
  {
    name: "Warrior III",
    sanskrit: "Virabhadrasana III",
    difficulty: "intermediate",
    tolerance: 1.25,
    description: "Balance on one leg; torso and other leg form a T-shape.",
    tips: [
      "Hips level, facing the floor",
      "Extend through fingertips and back heel",
      "Keep standing leg slightly soft",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 160,
      right_shoulder: 160,
      left_hip: 90,
      right_hip: 175,
      left_knee: 170,
      right_knee: 170,
    },
  },
  {
    name: "Triangle Pose",
    sanskrit: "Trikonasana",
    difficulty: "intermediate",
    tolerance: 1.2,
    description: "Wide stance, one hand toward shin/floor, other arm skyward.",
    tips: [
      "Stack shoulders vertically",
      "Lengthen both sides of the waist",
      "Do not lock the front knee",
    ],
    angles: {
      left_elbow: 170,
      right_elbow: 170,
      left_shoulder: 90,
      right_shoulder: 90,
      left_hip: 90,
      right_hip: 140,
      left_knee: 170,
      right_knee: 170,
    },
  },
];

export const PROGRESSION = {
  "Mountain Pose": "Raised Arms Pose",
  "Raised Arms Pose": "Chair Pose",
  "Chair Pose": "Warrior I",
  "Warrior I": "Warrior II",
  "Warrior II": "Triangle Pose",
  "Tree Pose": "Warrior III",
  "Goddess Pose": "Chair Pose",
  "Downward Dog": "Warrior I",
  "Warrior III": "Triangle Pose",
  "Triangle Pose": "Warrior III",
};

/** MediaPipe BlazePose landmark indices */
export const LM = {
  NOSE: 0,
  LEFT_SHOULDER: 11,
  RIGHT_SHOULDER: 12,
  LEFT_ELBOW: 13,
  RIGHT_ELBOW: 14,
  LEFT_WRIST: 15,
  RIGHT_WRIST: 16,
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
};

export const SKELETON_EDGES = [
  [LM.LEFT_SHOULDER, LM.RIGHT_SHOULDER],
  [LM.LEFT_SHOULDER, LM.LEFT_ELBOW],
  [LM.LEFT_ELBOW, LM.LEFT_WRIST],
  [LM.RIGHT_SHOULDER, LM.RIGHT_ELBOW],
  [LM.RIGHT_ELBOW, LM.RIGHT_WRIST],
  [LM.LEFT_SHOULDER, LM.LEFT_HIP],
  [LM.RIGHT_SHOULDER, LM.RIGHT_HIP],
  [LM.LEFT_HIP, LM.RIGHT_HIP],
  [LM.LEFT_HIP, LM.LEFT_KNEE],
  [LM.LEFT_KNEE, LM.LEFT_ANKLE],
  [LM.RIGHT_HIP, LM.RIGHT_KNEE],
  [LM.RIGHT_KNEE, LM.RIGHT_ANKLE],
];

export const JOINT_DEFS = {
  left_elbow: [LM.LEFT_SHOULDER, LM.LEFT_ELBOW, LM.LEFT_WRIST],
  right_elbow: [LM.RIGHT_SHOULDER, LM.RIGHT_ELBOW, LM.RIGHT_WRIST],
  left_shoulder: [LM.LEFT_ELBOW, LM.LEFT_SHOULDER, LM.LEFT_HIP],
  right_shoulder: [LM.RIGHT_ELBOW, LM.RIGHT_SHOULDER, LM.RIGHT_HIP],
  left_hip: [LM.LEFT_SHOULDER, LM.LEFT_HIP, LM.LEFT_KNEE],
  right_hip: [LM.RIGHT_SHOULDER, LM.RIGHT_HIP, LM.RIGHT_KNEE],
  left_knee: [LM.LEFT_HIP, LM.LEFT_KNEE, LM.LEFT_ANKLE],
  right_knee: [LM.RIGHT_HIP, LM.RIGHT_KNEE, LM.RIGHT_ANKLE],
};

export const MIRROR_JOINTS = {
  left_elbow: "right_elbow",
  right_elbow: "left_elbow",
  left_shoulder: "right_shoulder",
  right_shoulder: "left_shoulder",
  left_hip: "right_hip",
  right_hip: "left_hip",
  left_knee: "right_knee",
  right_knee: "left_knee",
};
